# ---------------------------------- Cluster -----------------------------------
#
cluster.name: elastic-cluster
#
# ------------------------------------ Node ------------------------------------
#
node.name: node-1
#
# ---------------------------------- Network -----------------------------------
#
network.host: 127.0.0.1
#
http.port: 9200
#transport.tcp.port: 9300
transport.port: 9300
#
# --------------------------------- Discovery ----------------------------------
#
discovery.seed_hosts: [ "127.0.0.1:9300", "127.0.0.1:9301", "127.0.0.1:9302" ]
#
cluster.initial_master_nodes: [ "node-1", "node-2", "node-3" ]
#

xpack.security.enabled: false
